#!/bin/bash

figlet mkcom
cowsay "By: ERIC NUNEZ"
sleep 2 
clear

read -p "What is the name of your command?: " name
clear
currentDir=$(pwd)
mv $currentDir/$name ~
cd ~
chmod 777 $name
export PATH=$PATH:~

